// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2bDoxpurk1ZyYE-CYwQRXrxRH9jvZ3E',
    appId: '1:245273466726:web:cb24b779ec97300b615aa7',
    messagingSenderId: '245273466726',
    projectId: 'visitor-managementapp',
    authDomain: 'visitor-managementapp.firebaseapp.com',
    storageBucket: 'visitor-managementapp.firebasestorage.app',
    measurementId: 'G-NWC3MKDRMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG_sGmIIEfsHl98DTI-84zmmuxHY_BTVU',
    appId: '1:245273466726:android:0831cf2a967fb490615aa7',
    messagingSenderId: '245273466726',
    projectId: 'visitor-managementapp',
    storageBucket: 'visitor-managementapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2CAT_HYFk9Bh930acTjvvVhf1ucREyfw',
    appId: '1:245273466726:ios:35a51bc660103b0f615aa7',
    messagingSenderId: '245273466726',
    projectId: 'visitor-managementapp',
    storageBucket: 'visitor-managementapp.firebasestorage.app',
    iosBundleId: 'com.example.visitorManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2CAT_HYFk9Bh930acTjvvVhf1ucREyfw',
    appId: '1:245273466726:ios:35a51bc660103b0f615aa7',
    messagingSenderId: '245273466726',
    projectId: 'visitor-managementapp',
    storageBucket: 'visitor-managementapp.firebasestorage.app',
    iosBundleId: 'com.example.visitorManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV2bDoxpurk1ZyYE-CYwQRXrxRH9jvZ3E',
    appId: '1:245273466726:web:6d89d6f12274b0be615aa7',
    messagingSenderId: '245273466726',
    projectId: 'visitor-managementapp',
    authDomain: 'visitor-managementapp.firebaseapp.com',
    storageBucket: 'visitor-managementapp.firebasestorage.app',
    measurementId: 'G-K4PB245Q2N',
  );
}
